export const books: Array<Book> = [
  {
    id: '1',
    title: 'Steve Jobs',
    author: 'Isaacson, Walter',
    year: 2011,
    imageUrl: 'https://covers.openlibrary.org/b/isbn/9781451648539-M.jpg',
    summary: 'Explore the riveting journey of a visionary co-founder who reshaped technology, personal computing, animation, music, phones, tablet computing, and digital publishing. This biography delves into the enigmatic personality, creative genius, and transformative impact of a trailblazing innovator. Uncover the brilliance and flaws that define one of the most influential figures in the world of technology, as this captivating narrative unfolds the story of a true icon.',
    isbn: '9781451648539',
    publisher: 'Simon & Schuster',
  },
  {
    id: '2',
    title: 'Antifragile',
    author: 'Taleb, Nassim Nicholas',
    year: 2014,
    imageUrl: 'https://covers.openlibrary.org/b/isbn/9780812979688-M.jpg',
    summary: 'Discover a paradigm-shifting exploration that challenges conventional wisdom on resilience. This thought-provoking guide unveils the concept of thriving in chaos, offering insights into systems that gain strength from disorder. With sharp observations, it redefines risk, resilience, and our understanding of uncertainty. Navigate through unconventional ideas that reshape perspectives, inviting readers to reconsider their approach to life&apos;s unpredictabilities. This concise and compelling narrative provides a new lens through which to view the inherent volatility of our world, encouraging a deeper understanding of thriving in the face of uncertainty.',
    isbn: '9780812979688',
    publisher: 'Random House Publishing Group',
  },
  {
    id: '3',
    title: 'Dress Your Family in Corduroy and Denim',
    author: 'Sedaris, David',
    year: 2004,
    imageUrl: 'https://covers.openlibrary.org/b/isbn/0316143464-M.jpg',
    summary: 'Embark on a hilarious and poignant journey through David Sedaris&apos; collection, as he invites readers into the eccentric world of his family and upbringing. With wit and insight, Sedaris shares humorous anecdotes and heartfelt reflections on his unconventional family life. From awkward childhood moments to quirky family dynamics, the stories in this volume paint a vivid picture of the author&apos;s unique experiences. This collection captivates with its blend of humor and sincerity, offering a charming exploration of the quirks and complexities that shape family bonds.',
    isbn: '0316143464',
    publisher: 'Little, Brown and Company',
  },
  {
    id: '4',
    title: 'The Immortal Life of Henrietta Lacks',
    author: 'Skloot, Rebecca',
    year: 2011,
    imageUrl: 'https://covers.openlibrary.org/b/isbn/9781400052189-M.jpg',
    summary: 'Embark on an engrossing exploration of a woman whose cells unknowingly catalyzed medical breakthroughs. In this compelling narrative, delve into the intertwined realms of science and ethics. The story revolves around an individual whose cellular legacy reshaped medical research, prompting profound reflections on the intersection of progress and human impact. With a poignant blend of personal history and scientific revelation, the account sheds light on enduring legacies and ethical considerations in the ever-evolving landscape of medical advancements.',
    isbn: '9781400052189',
    publisher: 'Broadway Paperbacks',
  },
  {
    id: '5',
    title: 'Deep Work',
    author: 'Newport, Cal',
    year: 2016,
    imageUrl: 'https://covers.openlibrary.org/b/isbn/9781455586691-M.jpg',
    summary: 'Embark on a transformative exploration delving into the essence of focused, meaningful work in a distracted world. This narrative navigates the challenges of the modern work environment, offering practical insights and strategies to harness the power of undistracted concentration. Through anecdotes and research, the account inspires a reevaluation of work approaches, urging readers to embrace a deeper, more focused engagement with their tasks amid the prevalent distractions of contemporary life.',
    isbn: '9781455586691',
    publisher: 'Grand Central Publishing',
  },
];